### ISSUE TITLE
Error in pip install .

### ISSUE THREAD

**Issue by EhsanMNA** [wandb/openui#112]
```
Building wheels for collected packages: openui, weave
  Building wheel for openui (pyproject.toml) ... done
  Created wheel for openui: filename=openui-0.2-py3-none-any.whl size=19572 sha256=95fee785df95cf0d1a7b1287b5dfeec9454d44f20dd6d74dfd03de1c49bff9bb
  Stored in directory: C:\Users\Hi\AppData\Local\Temp\pip-ephem-wheel-cache-ojleeclj\wheels\a3\95\30\27f46e35bfa6c3aa9fb132c28664a29c360846fc4d05998034
  Building wheel for weave (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for weave (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [71 lines of output]
      running bdist_wheel
      running build
      Traceback (most recent call last):
        File "<string>", line 56, in download_and_extract_tarball
        File "C:\Python312\Lib\urllib\request.py", line 240, in urlretrieve
          with contextlib.closing(urlopen(url, data)) as fp:
                                  ^^^^^^^^^^^^^^^^^^
        File "C:\Python312\Lib\urllib\request.py", line 215, in urlopen
          return opener.open(url, data, timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python312\Lib\urllib\request.py", line 521, in open
          response = meth(req, response)
                     ^^^^^^^^^^^^^^^^^^^
        File "C:\Python312\Lib\urllib\request.py", line 630, in http_response
          response = self.parent.error(
                     ^^^^^^^^^^^^^^^^^^
        File "C:\Python312\Lib\urllib\request.py", line 559, in error
          return self._call_chain(*args)
                 ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python312\Lib\urllib\request.py", line 492, in _call_chain
          result = func(*args)
                   ^^^^^^^^^^^
        File "C:\Python312\Lib\urllib\request.py", line 639, in http_error_default
          raise HTTPError(req.full_url, code, msg, hdrs, fp)
      urllib.error.HTTPError: HTTP Error 403: Forbidden

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\Hi\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Hi\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Hi\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Hi\AppData\Local\Temp\pip-build-env-lcsryw8s\overlay\Lib\site-packages\setuptools\build_meta.py", line 410, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Hi\AppData\Local\Temp\pip-build-env-lcsryw8s\overlay\Lib\site-packages\setuptools\build_meta.py", line 395, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\Hi\AppData\Local\Temp\pip-build-env-lcsryw8s\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 108, in <module>
        File "C:\Users\Hi\AppData\Local\Temp\pip-build-env-lcsryw8s\overlay\Lib\site-packages\setuptools\__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Hi\AppData\Local\Temp\pip-build-env-lcsryw8s\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\Hi\AppData\Local\Temp\pip-build-env-lcsryw8s\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
          dist.run_commands()
        File "C:\Users\Hi\AppData\Local\Temp\pip-build-env-lcsryw8s\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\Hi\AppData\Local\Temp\pip-build-env-lcsryw8s\overlay\Lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "C:\Users\Hi\AppData\Local\Temp\pip-build-env-lcsryw8s\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Hi\AppData\Local\Temp\pip-build-env-lcsryw8s\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\Hi\AppData\Local\Temp\pip-build-env-lcsryw8s\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Hi\AppData\Local\Temp\pip-build-env-lcsryw8s\overlay\Lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "C:\Users\Hi\AppData\Local\Temp\pip-build-env-lcsryw8s\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 86, in run
        File "<string>", line 76, in download_frontend
        File "<string>", line 58, in download_and_extract_tarball
      RuntimeError: Couldn't download the tarball https://storage.googleapis.com/wandb-cdn-prod/weave/f9114af272a3b157866ac1b46efa139cd2411de1.tar.gz due to error: HTTP Error 403: Forbidden
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for weave
Successfully built openui
Failed to build weave
ERROR: Could not build wheels for weave, which is required to install pyproject.toml-based projects
```

**Comment by SFARPak** [comment]
I believe this error occurs when you have network down, did you try installing again?

urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by EhsanMNA** [comment]
Seems like i should use a proxy for that, thx
