### ISSUE TITLE
Coroutine problem

### ISSUE THREAD

**Issue by SOUMYABROTOBANERJEE** [wandb/openui#12]
I am facing a coroutine problem using openai
![image](https://github.com/wandb/openui/assets/38866769/bdec09a8-e763-4f97-bba6-0a873409b4f8)

**Comment by vanpelt** [comment]
This should be fixed now.  You can pull from master and re-install or just install in dev mode.  If it's still happening, unset your WANDB_API_KEY with:

```
WANDB_API_KEY= python -m openui
```

Let me know if not and share some more of the stacktrace so I can see what's up.

**Comment by butzhang** [comment]
i still got the error

```
WANDB_API_KEY= python -m openui
INFO (openui):  Starting OpenUI AI Server created by W&B...
INFO (openui):  Running API Server
Logged in as W&B user ke-zhang-rock.
View Weave data at https://wandb.ai/no-1-zone-team/openui-test-21/weave
INFO (uvicorn.error):  Started server process [42712]
INFO (uvicorn.error):  Waiting for application startup.
DEBUG (openui):  Starting up server in 42712...
INFO (uvicorn.error):  Application startup complete.
INFO (uvicorn.error):  Uvicorn running on http://127.0.0.1:7878 (Press CTRL+C to quit)
INFO (uvicorn.access):  127.0.0.1:54824 - "GET / HTTP/1.1" 200
INFO (uvicorn.access):  127.0.0.1:54824 - "GET /assets/index-2-rOUq-J.js HTTP/1.1" 304
INFO (uvicorn.access):  127.0.0.1:54825 - "GET /assets/index-OfmkY5JK.css HTTP/1.1" 304
INFO (uvicorn.access):  127.0.0.1:54824 - "GET /assets/textarea-4A01Dc6n.js HTTP/1.1" 304
INFO (uvicorn.access):  127.0.0.1:54825 - "GET /assets/index-VsdO9OoH.js HTTP/1.1" 304
INFO (uvicorn.access):  127.0.0.1:54825 - "GET /v1/session HTTP/1.1" 200
INFO (uvicorn.access):  127.0.0.1:54825 - "GET /assets/Builder-b4JJdzJb.js HTTP/1.1" 304
INFO (uvicorn.access):  127.0.0.1:54825 - "POST /v1/chat/completions HTTP/1.1" 200
ERROR (openui):  Server Error: unhandled errors in a TaskGroup (1 sub-exception)
Traceback (most recent call last):
  File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/responses.py", line 264, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/responses.py", line 260, in wrap
    await func()
  File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/responses.py", line 237, in listen_for_disconnect
    message = await receive()
  File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 535, in receive
    await self.message_event.wait()
  File "/opt/homebrew/Cellar/python@3.10/3.10.13_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 15453ee30

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/middleware/sessions.py", line 83, in __call__
  |     await self.app(scope, receive, send_wrapper)
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
  |     await route.handle(scope, receive, send)
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 299, in handle
  |     await self.app(scope, receive, send)
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 79, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
  |     await response(scope, receive, send)
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/responses.py", line 257, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/responses.py", line 260, in wrap
    |     await func()
    |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/responses.py", line 249, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/Users/kezhang/src/openui/backend/openui/openai.py", line 15, in openai_stream_generator
    |     async for chunk in subscription:
    | TypeError: 'async for' requires an object with __aiter__ method, got coroutine
    +------------------------------------
ERROR (uvicorn.error):  Exception in ASGI application
Traceback (most recent call last):
  File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/responses.py", line 264, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/responses.py", line 260, in wrap
    await func()
  File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/responses.py", line 237, in listen_for_disconnect
    message = await receive()
  File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 535, in receive
    await self.message_event.wait()
  File "/opt/homebrew/Cellar/python@3.10/3.10.13_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 15453ee30

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
  |     return await self.app(scope, receive, send)
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
  |     raise exc
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/middleware/sessions.py", line 83, in __call__
  |     await self.app(scope, receive, send_wrapper)
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
  |     await route.handle(scope, receive, send)
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 299, in handle
  |     await self.app(scope, receive, send)
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 79, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
  |     await response(scope, receive, send)
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/responses.py", line 257, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/responses.py", line 260, in wrap
    |     await func()
    |   File "/Users/kezhang/src/openui/backend/venv/lib/python3.10/site-packages/starlette/responses.py", line 249, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/Users/kezhang/src/openui/backend/openui/openai.py", line 15, in openai_stream_generator
    |     async for chunk in subscription:
    | TypeError: 'async for' requires an object with __aiter__ method, got coroutine
    +------------------------------------
```

**Comment by raphant** [comment]
Same here.
After adding a `print(type(subscription))` to `openai_stream_generator`, it seems that `subscription` returns as a coroutine.

Adding the following before the for loop temporarily solves the issue:

```python
    if asyncio.iscoroutine(subscription_coroutine):
        subscription = await subscription_coroutine
    else:
        subscription = subscription_coroutine
```

**Comment by SOUMYABROTOBANERJEE** [comment]
The issue can also be fixed by removing wand & weave imports for now if tracking is not essential.

**Comment by vanpelt** [comment]
Appologies here, I just disabled the call to `weave.init` in server which will resolve this entirely.  There's a bug where it doesn't like the way I'm using generators.  Installing from master will resolve this issue.
