### ISSUE TITLE
ModuleNotFoundError: No module named 'openui.db'

### ISSUE THREAD

**Issue by hiptodude2** [wandb/openui#27]
# error:
PS C:\Users\alright\Desktop\that is him> python -m openui
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\alright\anaconda3\Lib\site-packages\openui\__main__.py", line 3, in <module>
    from . import server
  File "C:\Users\alright\anaconda3\Lib\site-packages\openui\server.py", line 30, in <module> 
    from .session import DBSessionStore, SessionData
  File "C:\Users\alright\anaconda3\Lib\site-packages\openui\session.py", line 5, in <module> 
    from .db.models import Session, ensure_migrated, Usage
ModuleNotFoundError: No module named 'openui.db'

how could you fix it?

**Comment by vanpelt** [comment]
Hmm, this is odd.  You might be able to add `openui.db` to [this list](https://github.com/wandb/openui/blob/main/backend/pyproject.toml#L27) and rebuild but not sure you want to bark up that tree.  The other thing to do would be to run the following and see if this works:

```
pip uninstall openui
cd ./backend
pip install -e .
python -m openui
```

Let me know if you're still getting the error, seems like it's something funky with your python environment.
