### ISSUE TITLE
Error! 401 Login required to use OpenUI

### ISSUE THREAD

**Issue by JulesPad** [wandb/openui#7]
Amazing work! But after installing it and running into the weave issue, installing it back to the 0.44.0 version worked for me. 

I export my openai api key.

Then I get prompted to paste an W&B API key, which I did. Then server started running and when trying to send a message I get this error.

```
ERROR (openui):  HTTP Error: 401: Login required to use OpenUI
Traceback (most recent call last):
  File "/Users/julespadova/Documents/mirai. master folder/Automated UX design test/openui/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/julespadova/Documents/mirai. master folder/Automated UX design test/openui/lib/python3.10/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
  File "/Users/julespadova/Documents/mirai. master folder/Automated UX design test/openui/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/Users/julespadova/Documents/mirai. master folder/Automated UX design test/openui/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/julespadova/Documents/mirai. master folder/Automated UX design test/openui/backend/openui/server.py", line 94, in chat_completions
    raise HTTPException(status_code=401, detail="Login required to use OpenUI")
fastapi.exceptions.HTTPException: 401: Login required to use OpenUI
```

I then logged in with W&B thinking I needed to do it with their package but the error persists. 

<img width="1397" alt="image" src="https://github.com/wandb/openui/assets/62508133/92b610de-5b15-4250-882a-2483d914cc58">

**Comment by butzhang** [comment]
+1. I also has this issue. As a workround, we can just comment out the authorization code

**Comment by butzhang** [comment]
> +1. I also has this issue. As a workround, we can just comment out the authorization code

Still doesn't work after I manually set user_id. Can't even make this app work.

**Comment by vanpelt** [comment]
Sorry guys, I didn’t test the local env well outside of my environment.  I’ll get this fixed this afternoon and report back!

**Comment by vanpelt** [comment]
One quick fix could be to set `OPENUI_ENVIRONMENT=local` I shouldn’t be requiring login when you’re running it yourself, although I thought this was the default.  Again, will fix today!

**Comment by rossman22590** [comment]
tried this and still got Error! 401 Login required to use OpenUI

**Comment by rossman22590** [comment]
127.0.0.1:55653 - "POST /v1/chat/completions HTTP/1.1" 401 Unauthorized

**Comment by butzhang** [comment]
> Sorry guys, I didn’t test the local env well outside of my environment. I’ll get this fixed this afternoon and report back!

Np! Thanks for working on it!

**Comment by vanpelt** [comment]
Ok folks, this should be fixed now.  I'm going to write some automated tests tomorrow to prevent this from happening in the future.  There are still likely an issue or two with the Ollama logic, but if you set your OPENAI_API_KEY it should work.
