### ISSUE TITLE
Error: while installing, something related to fastapi

### ISSUE THREAD

**Issue by sarkaramitabh300** [wandb/openui#78]
Collecting fastapi>=0.108.0 (from openui==0.2)
  Using cached fastapi-0.109.2-py3-none-any.whl.metadata (25 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/amitabhsarkar/anaconda3/envs/myenv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/Users/amitabhsarkar/anaconda3/envs/myenv/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "/Users/amitabhsarkar/anaconda3/envs/myenv/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/Users/amitabhsarkar/anaconda3/envs/myenv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "/Users/amitabhsarkar/anaconda3/envs/myenv/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/amitabhsarkar/anaconda3/envs/myenv/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 457, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000

**Comment by vanpelt** [comment]
Hmm, looks like your environment is messed up.  Here's what I would try.

1. Try upgrading pip `python -m pip install --upgrade pip`
2. pip uninstall fastapi
3. If that doesn't work, try creating a clean virtual environment

**Comment by sarkaramitabh300** [comment]
> 2\. pip uninstall fastapi

thanks for the reply, I tried this, after running pip install .  I am getting a new issue,
 error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet https://github.com/wandb/weave.git /private/var/folders/11/y43qcy3d5yb4gf7f1sfdffm80000gp/T/pip-install-p6938ebp/weave_1851406e5a5b439e998ccaa845f1d842 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/wandb/weave.git /private/var/folders/11/y43qcy3d5yb4gf7f1sfdffm80000gp/T/pip-install-p6938ebp/weave_1851406e5a5b439e998ccaa845f1d842 did not run successfully.
│ exit code: 128
╰─> See above for output.

**Comment by vanpelt** [comment]
Try replacing the git weave URL in pyproject.toml with "weave" and it should work.
