### ISSUE TITLE
Does not work automatically with Ollama

### ISSUE THREAD

**Issue by sdrshn-nmbr** [wandb/openui#8]
This is the error I am getting

(venv) PS C:\Users\suddu\Downloads\Python\ML\AI\openui\backend> python -m openui
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\suddu\Downloads\Python\ML\AI\openui\backend\openui\__main__.py", line 3, in <module>
    from . import server
  File "C:\Users\suddu\Downloads\Python\ML\AI\openui\backend\openui\server.py", line 32, in <module>
    from .ollama import ollama_stream_generator, openai_to_ollama
  File "C:\Users\suddu\Downloads\Python\ML\AI\openui\backend\openui\ollama.py", line 7, in <module>
    from weave.monitoring.openai.util import (
ImportError: cannot import name 'reconstruct_completion' from 'weave.monitoring.openai.util'

**Comment by JulesPad** [comment]
This is the same issue that was in another issue that is now closed. You can find it here: https://github.com/wandb/openui/issues/6

**Comment by vanpelt** [comment]
Sorry guys, should be fixed on master.  You may need to first uninstall than reinstall to get the change.  Alternatively you can run `pip install weave==0.40.0`
